### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by MarkJThomas** [persts/BBoxEE#1]
Hiya,

I don't have any issues, well, I have loaded the interface but have no idea how to load images and how to use the application for camera trap images.

Any further info you can provide I will be eternally grateful

All the best
Mark

**Comment by persts** [comment]
@MarkJThomas We had planned on releasing a series of short videos this very week but ran into a few delays. I will try to put together a very basic quick start guide by the end of the week.

**Comment by MarkJThomas** [comment]
Many thanks @persts I will be starting a camera trap research project in the tropics next week in which I hope to use this tool. I can also provide feedback if you would like.
All the best!
Mark

**Comment by persts** [comment]
@MarkJThomas I have created a very basic [quick start guide](https://github.com/persts/BBoxEE/blob/master/doc/Quick%20Start%20Guide.pdf) and added some demo data. 

If you want to set up a quick call use the [contact us](http://biodiversityinformatics.amnh.org/ml4conservation/animal-detection-network/) button on our ml4conservation page.

We would love any feedback and are always looking for contributors, especially when it comes to documentation.
