### ISSUE TITLE
Feature Request -- "Skip to NA" Button

### ISSUE THREAD

**Issue by nnonlamb** [persts/BBoxEE#10]
When I go to export my data, sometimes I find a technician has forgotten to label the boxes they drew for a batch, and it's left me with multiple NA labels across multiple .bbx files. I'm not able to simply relabel the NA to the correct species in the export tab because it will often include multiple species. Would it be possible to create a "Skip to Next NA Labelled Photo" button to the Annotate Tab, similar to the "Skip to Next Photo Containing a Bounding Box"? Then I wouldn't waste an hour searching each .bbx that has an NA label somewhere in it.

**Comment by persts** [comment]
This has been on my todo list for a while. I think there will need to be two different features: One on the Export tab so you can find which bbx files contain a certain class and then one on the annotation tab to find specific images with bboxes labeled as a specific class. Have not decided if these should be a filter behavior or just a simple dialog with a list.

**Comment by persts** [comment]
Last commit has some basic functionality.
