### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by VLucet** [persts/BBoxEE#19]
Hi! I like the app, I find the auto-annotator very neat. I am reviewing existing tools for annotation camera trap data, and I was wondering whether you had plans to add features to the app, and in general what is the status of development on that project.

**Comment by persts** [comment]
@VLucet The assisted annotation was something that set BBoxEE apart from other annotators when it was first started, but it has taken a while to get to this point as I don't have dedicated funding for this project. 

Generally speaking, all of the planned functionality is in the core app. There is an intern working on adding a some final touches to the filter/search tools. I just upgraded it to Qt6 the other day, so I still need to do some testing to make sure nothing was missed. 

I will be adding an additional cloud and CPW Photo warehouse script for Torch base models and hopefully some additional tutorials or a more detailed user manual (though I would love to find someone interested in taking that on). When time permits, the code could use some serious refactoring to make it a little more manageable. 

If you are interested in speaking more I can reach out to you over email.
