### ISSUE TITLE
Recommendation for Feature -- Evaluating Accuracy

### ISSUE THREAD

**Issue by nnonlamb** [persts/BBoxEE#2]
Some sort of method to track accuracy of the imported model once the assisted annotation has been used on a dataset

Possible option:
-track changes to bboxes (adjustments to bbox dimensions and changes in class)
-provides a % and real number of bboxes adjusted, and divided by dimension changes versus class changes
-possible to incorporate a type 1 and type 2 error rate for whole batch? Per class in batch?

**Comment by persts** [comment]
@nnonlamb YES! It is on the todo list and I hope have something available in the coming weeks.

**Comment by persts** [comment]
Some basic accuracy reporting has been added in the the last commit.
