### ISSUE TITLE
Recommendation for Feature -- Confidence Rates on BBoxes

### ISSUE THREAD

**Issue by nnonlamb** [persts/BBoxEE#3]
feature that reports model's confidence level for bboxes created with the assisted annotation tool
-incorporate an additional feature to "flag" boxes below a preset threshold of confidence for manual review?

**Comment by persts** [comment]
Model confidence values are now displayed in the label table an on the bounding box label.

When using the assisted annotation, all images should be reviewed not just ones below a certain threshold as the intent is these model generate bounding boxes will be used in future training.

I can see some value in flagging an image as needing additional review or special attention but would like to see other comment on such a feature. I think this will become a separate issue.
