### ISSUE TITLE
Bug Report -- Unpredictable Crashes

### ISSUE THREAD

**Issue by nnonlamb** [persts/BBoxEE#4]
bboxee will sometimes crash during manual annotation. Not yet found a common denominator, but it occurs on my work computer (desktop hooked into a high-security network server) and on an employees laptop (standard laptop not connected to any network).

Only pattern is crashing after at least a few hundred photos have been labeled. Does not occur every time, or even most times, or on particular days, or while anything else is/isn't running simultaneously. Very unpredictable when it will crash. Does not corrupt the .bbx file, but loses any unsaved progress.

**Comment by persts** [comment]
@nnonlamb What OS? Are you running directly from source or using a packaged version made with something like pyinstaller?

I too have experienced a similar situation on Linux when I use multiple GPUs and the assisted annotation. As I am running from source I can see there is no python error, just a straight up core dump. I can't reproduce it regularly so I have not been able to run it through a debugger but I suspect it may not be the BBoxEE code itself. I have not experienced any similar crash when only using a single GPU.

**Comment by nnonlamb** [comment]
Both using Windows 10. Both using the .exe you provided.

Neither computer has a GPU either

**Comment by persts** [comment]
Ah. They are experimental. I will see about rolling another version with a console and debugging to see if we can catch something about the crash.

**Comment by persts** [comment]
If hit the space bar, and advance to the next image, while in the middle of drawing a bounding box it will cause a crash. This has just been fixed, but I will keep this open until I get you the next packaged version.

**Comment by persts** [comment]
I think I have found and fixed the problem that most likely was causing the issue. I will send you a link to download the newest compiled version and will close this ticket for now.
