### ISSUE TITLE
How to -- BBoxEE to CPW PW "Groups" and "Details"

### ISSUE THREAD

**Issue by nnonlamb** [persts/BBoxEE#6]
there is a feature in CPW PhotoWarehouse that describes the species in terms of an overarching "Group" (ex, ungulate for elk) and you can incorporate further "Details" into a particular species identification (ex, calf for elk). Is there a way to incorporate this information when transferring this kind of data over if we use, for example, hierarchical modeling?

Ex:
(Species Model) --> "Elk" label
(Elk Details Model) --> "Calf" label
(Transfer to PW) --> Ungulate Group, Elk Species, Calf Detail
**group would be filled out automatically since each species can only be one group

**Comment by persts** [comment]
This is something that would be done outside of BBoxEE once you have a production model.

In the database-tools folder there is an example how to use a model to directly import data into CPW PW. You would basically just need to expand upon [this section](https://github.com/persts/BBoxEE/blob/bf1cc00eb40f57194d6a5dc4e97a10946aaa6c36/database-tools/cpwpw.py#L195-L226) of the code.
