### ISSUE TITLE
Feature Request -- Auto-assign Blurry Images in Visit Event

### ISSUE THREAD

**Issue by nnonlamb** [persts/BBoxEE#8]
something that allows BBoxEE to assume a blurry photo's class assignment based on the other photos within the same trigger event.

Ex: [elk passes through camera site]
IMG01 = elk on left
IMG02 = elk at center
IMG03 = blurry (elk right up next to camera lens)
ImG04 = elk on right
--> BBoxEE assigns "elk" to IMG03 based on assignments for IMG01, IMG02, and IMG04

Considerations:
1. Would this require use of the photo metadata to read timestamps and identify the photos that are within the same event, or would this be done by assuming the photos immediately adjacent to the "unknown" photo are relevant?
2. How would this resolve if the photos used are not equal? Ex, [2 elk] [unknown] [1 elk]?
3. I assume since the AI cannot distinguish a "blurry" definition very intuitively, measuring low confidence would be a better approach?

**Comment by persts** [comment]
This is outside of the scope of core BBoxEE functionality. This could be accomplished with a post processing pipeline.
